# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-kernel:
    docker:
      - image: archlinux/latest
    steps:
      - checkout
      - run:
          name: "Download deps"
          command: "pacman -Syu fmt meson clang"
      - run:
          name: "Meson configure"
          command: "CC=clang CXX=clang++ meson setup build --buildtype debug -Ddebug_log_mmap=false"
      - run: 
          name: "Change directory"
          command: "cd build"
      - run:
          name: "Build kernel"
          command: "ninja kernel.img -j$(nproc)"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  kernel-workflow:
    jobs:
      - build-kernel
