# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-kernel:
    docker:
      - image: archlinux:latest
    steps:
      - checkout
      - run:
          name: "Download deps"
          command: "sudo pacman -Sy fmt qemu-full pkgconf gdb mtools parted clang meson -y --needed --noconfirm"
      - run:
          name: "Meson configure"
          command: "CC=clang CXX=clang++ meson setup build --buildtype debug -Ddebug_log_mmap=false"
      - run:
          name: "Build kernel"
          command: "ninja -C build kernel.img -j$(nproc)"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  kernel-workflow:
    jobs:
      - build-kernel
